reports errors when creating app domain

diff --git a/phd b/phd
--- a/phd
+++ b/phd
@@ -56,7 +56,14 @@ if [[ ! "$base" =~ "." ]]; then
   ip=`ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`
   echo "Setting up DNS..."
   echo ""
-  output=`curl -s https://manager2.webbynode.com/api/domain.json?ip=$ip&app_name=$base`
+  output=`curl -s https://manager2.webbynode.com/api/domain.json?ip=$ip\&app_name=$base`
+
+  if [ "$?" != "0" ]; then
+    echo "$output" >> /var/webbynode/log/domain_error.log
+    echo "Could not create a domain for your application. Check /var/webbynode/log/domain_error.log for more information."
+    exit 1
+  fi
+
   name=`echo "$output" | sed -e 's/[{}]/''/g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | grep "name" | cut -d ':' -f 2 | sed -e 's/"//g'`
   host="$name"
 fi
